### PR TITLE
rendered data on list.jsx component

### PR DESCRIPTION
**Pull request by SinfulHymn**
## Description

In the List.jsx component the 'data' prop was used to render the items in the list. 
Data was iterated using the .map() function and returns jsx component ListItem with all item names and uses id as key.

## Related Issue

closes 1 

## Acceptance Criteria
- [x] The `streamListItems` function is used in `App.jsx` to get the items in the current list from the Firestore database
- [x] The list is passed into the `List` component as a prop named `data`
- [x] In `List.jsx`, the `ListItem` component is used to render the name of each item

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### Before

n/a

### After

n/a

## Testing Steps / QA Criteria

n/a

### CODE REVIEW

**Comment by a-fink** [comment]
Looks good to me. My only thought would be maybe comment out the console log, but we could do that later during cleanup before going into production as well.

**Comment by a-fink** [comment]
Sorry!! Meant to hit comment and accidentally hit close with comment.

**Comment by Amanda2900** [comment]
Looks good to me too!

**Review by Amanda2900 — COMMENTED** [review]
Looks good to me!

**Review by thetrend — APPROVED** [review]
Looks great! 🎉

**Comment by ameliasheppy** [comment]
Thanks guys!

**Pull request merged**
